# Markdown rendering of validation_report(), for the copy of the report that
# lives in the repository and renders natively on GitHub. Generated, never
# hand-edited: the CI workflow regenerates it and fails if the committed file
# differs, so a number in the repo cannot drift away from what the engine
# actually fits.
#
# Same data as validation_report_html(), traded down to what a markdown table
# can carry: per-row notes become footnotes under their table, and the tolerance
# headroom becomes a percentage instead of a bar.

.vm_cell <- function(x) gsub("|", "\\|", as.character(x), fixed = TRUE)

.vm_pct <- function(x) {
  if (is.na(x)) return("")
  if (x == 0) return("0")
  if (x < 0.001) return("<0.1%")
  paste0(trimws(formatC(100 * x, format = "fg", digits = 2)), "%")
}

# Literal characters rather than HTML entities: GitHub sanitises rendered
# markdown, and these have to survive that as well as a plain-text read.
#
# A `divergent` row that passes gets its own mark. It passed against what this
# engine is expected to produce, not against the reference value beside it, and
# a tick next to two visibly different numbers would read as a claim they match.
.vm_mark <- function(kind, verdict) {
  if (identical(verdict, "fail")) return("✗")
  if (identical(verdict, "pass"))
    return(switch(kind, divergent = "≠", regression = "=", "✓"))
  if (identical(verdict, "missing")) return("?")
  "–"
}

# The provenance block above each table: what was actually measured, on what,
# under which guideline, and where it was published. Without this a reference
# value is just a number someone typed.
.vm_provenance <- function(spec, exp) {
  e <- exp[exp$experiment == (spec$experiment %||% ""), , drop = FALSE]
  if (nrow(e) != 1) return(character(0))
  e <- e[1, ]
  field <- function(name, value)
    if (is.na(value) || !nzchar(value)) NULL else
      sprintf("| **%s** | %s |", name, .vm_cell(value))

  rows <- c(
    field("Experiment", e$label),
    field("Organism", e$organism),
    field("Life stage", e$life_stage),
    field("Endpoint", spec$endpoint %||% e$endpoint),
    field("Exposure", sprintf("%s days", e$duration_days)),
    field("Guideline", e$guideline),
    field("Soil", e$soil),
    field("Units", e$units),
    field("Mixture ratios", e$ratios),
    field("Published in", sprintf("%s — [doi:%s](https://doi.org/%s)",
                                  e$publication, e$doi, e$doi)),
    field("Raw data", sprintf("[doi:%s](https://doi.org/%s)",
                              e$data_doi, e$data_doi)))

  caveats <- trimws(strsplit(e$caveats %||% "", "|", fixed = TRUE)[[1]])
  caveats <- caveats[nzchar(caveats)]

  c("<details><summary>Provenance</summary>", "",
    "| | |", "|---|---|", rows, "",
    if (length(caveats))
      c("**Caveats for this experiment**", "",
        paste0("- ", vapply(caveats, .vm_cell, character(1))), "")
    else NULL,
    "</details>", "")
}

#' Render a validation report as markdown
#'
#' @param report A [validation_report()] data frame.
#' @param path File to write, or `NULL` to return the markdown as a character
#'   vector without writing.
#' @return The markdown lines, invisibly when written to a file.
#' @export
validation_report_md <- function(report, path = "VALIDATION.md") {
  reg <- validation_datasets()
  exp <- validation_experiments()
  n_match <- sum(report$kind == "match")
  n_pass  <- sum(report$kind == "match" & report$verdict == "pass")
  n_fail  <- sum(report$verdict == "fail")
  n_div   <- sum(report$kind == "divergent")

  out <- c(
    "# Validation report",
    "",
    paste0("<!-- Generated by tools/validation-report.R. Do not edit by hand: ",
           "CI regenerates this file and fails if it differs. -->"),
    "",
    # Deliberately no timestamp: the file is regenerated on every CI run and
    # diffed against the committed copy, so a clock in it would fail that check
    # every time. Git history already records when the numbers last moved.
    sprintf(paste0("**%d of %d** reference values reproduced, ",
                   "%d deliberate difference%s, %d failure%s."),
            n_pass, n_match, n_div, if (n_div == 1) "" else "s",
            n_fail, if (n_fail == 1) "" else "s"),
    "",
    paste0("Every figure in the `mixdra` column was produced by re-fitting the ",
           "reference datasets with the current version of the package. The ",
           "`Reference` column comes from ",
           "[`inst/validation/oracles.csv`](inst/validation/oracles.csv), which ",
           "records each value together with where it was read from, and which ",
           "is also what the test suite asserts against. A number cannot appear ",
           "here without being tested, or be tested without appearing here."),
    "",
    paste0("Reference values come from two places. Rows sourced from the ",
           "**publication** are values printed in the peer-reviewed paper: ",
           "citable, and independent of the spreadsheet the data was extracted ",
           "from. Rows sourced from the **workbook** are cells in the ",
           "MixTox/Excel workbook itself, which covers quantities the paper ",
           "does not print. Not every quantity is comparable across the two — ",
           "the published single-compound curves are fitted per compound with ",
           "their own upper asymptote, while the mixture model shares one — and ",
           "where that matters the row says so."),
    "",
    "### Two fitting designs, and why a residual can look worse",
    "",
    paste0("A mixture can look more toxic than expected for two different ",
           "reasons: the chemicals interact, or one of them is simply more ",
           "potent than its own curve suggested. Both explanations fit the ",
           "data about equally well, and an optimiser has no way to prefer ",
           "one — it takes whichever lowers the residual, which usually means ",
           "quietly moving the curve and reporting no interaction."),
    "",
    paste0("This engine fits each chemical's curve from the single-compound ",
           "data alone and then holds it fixed, so the mixture data can only ",
           "answer one question: how far does it deviate? That is the **staged** ",
           "design. It has fewer free parameters than a **joint** fit, which ",
           "re-estimates the curves on the mixture data too, and so it always ",
           "leaves a larger residual. That is the price of the sharper ",
           "question, not a worse fit."),
    "",
    paste0("Because the binary reference values were produced jointly, those ",
           "datasets are reported both ways. The `joint refit` rows fit the ",
           "reference model exactly as the workbook did and land on its ",
           "residual, which is what shows the larger staged residual below them ",
           "to be the model rather than the arithmetic. The ternary reference ",
           "values were themselves produced with a staged fit, so they compare ",
           "directly and no second fit is needed."),
    "",
    paste0("**Diff** is the distance from the reference value. **Tol.** is how ",
           "much of the allowed tolerance that distance uses — a low ",
           "percentage is a strong agreement, near 100% only just qualifies."),
    "",
    paste0("The last column reads: **✓** the engine matches the reference; ",
           "**≠** it disagrees with the reference on purpose — read the ",
           "footnote; **=** there is no published counterpart, and the value is ",
           "pinned against what this engine produced before, to catch a ",
           "regression in the fitter; **✗** it failed; **–** no point value is ",
           "claimed, and the bound is asserted in the test suite instead."),
    "",
    paste0("Only the **✓** rows count towards the score above. A regression pin ",
           "is a claim about this engine's own stability, not about reproducing ",
           "anyone else's result, and counting it as evidence of the latter ",
           "would overstate the case."),
    "")

  for (ds in unique(report$dataset)) {
    d <- report[report$dataset == ds, , drop = FALSE]
    # Footnote only the rows that need explaining, numbered within the table.
    fn <- ifelse(nzchar(d$note), cumsum(nzchar(d$note)), NA_integer_)
    out <- c(out,
      sprintf("## %s", .vm_cell(reg[[ds]]$title %||% ds)),
      "",
      sprintf("`%s`", .vm_cell(ds)),
      "",
      .vm_provenance(reg[[ds]], exp),
      "| Quantity | Reference | mixdra | Diff | Tol. | |",
      "|---|---:|---:|---:|---:|:-:|")
    for (i in seq_len(nrow(d))) {
      tol <- suppressWarnings(as.numeric(d$tolerance[i]))
      used <- if (is.na(tol) || tol <= 0 || is.na(d$rel_diff[i])) ""
              else .vm_pct(d$rel_diff[i] / tol)
      out <- c(out, sprintf("| %s%s | %s | %s | %s | %s | %s |",
        .vm_cell(d$label[i]),
        if (is.na(fn[i])) "" else sprintf(" [^%s-%d]", ds, fn[i]),
        if (is.na(d$reference[i])) "" else paste0("`", .vm_cell(.vh_num(d$reference[i])), "`"),
        if (is.na(d$observed[i])) "" else paste0("`", .vm_cell(.vh_num(d$observed[i])), "`"),
        .vm_pct(d$rel_diff_reference[i]), used,
        .vm_mark(d$kind[i], d$verdict[i])))
    }
    out <- c(out, "")
    for (i in which(!is.na(fn)))
      out <- c(out, sprintf("[^%s-%d]: %s%s", ds, fn[i],
                            if (nzchar(d$source[i]))
                              sprintf("*%s — %s.* ", .vm_cell(d$source_type[i]),
                                      .vm_cell(d$source[i])) else "",
                            .vm_cell(d$note[i])), "")
  }

  out <- c(out,
    "## What this report does not show",
    "",
    paste0("Two implementations agreeing shows that they agree. It does not ",
           "show that either is right. That is what the synthetic recovery ",
           "tests are for: data is generated forward from known parameters ",
           "through the same model the fitter uses, and the engine has to ",
           "invert it back to those parameters. Those live in ",
           "[`tests/testthat/test-recovery.R`](tests/testthat/test-recovery.R)."),
    "",
    paste0("Nor does it cover every fixture in the repository. Three ",
           "laboratory experiments produced four ternary mixtures and eleven ",
           "binary pairs; only the datasets listed above carry reference values ",
           "so far. Registering the rest is a matter of adding rows to the ",
           "oracle table, not new code."),
    "",
    paste0("Reference data are *Folsomia candida* soil reproduction assays ",
           "(chlorpyrifos, microplastics, imidacloprid and FBSA), fitted with ",
           "the Jonker et al. (2005) mixture dose-response method. The raw ",
           "survival and reproduction data are openly available at ",
           "[doi:10.5281/zenodo.14961673]",
           "(https://doi.org/10.5281/zenodo.14961673)."),
    "")

  if (is.null(path)) return(out)
  writeLines(out, path, useBytes = TRUE)
  invisible(out)
}

#' Write the validation badges into a README
#'
#' Rewrites whatever sits between the `validation-badges` markers with badges
#' carrying the current score, so the figure in the README is generated rather
#' than typed. The CI workflow regenerates and diffs this file, which is what
#' stops the badge going stale while still claiming a number.
#'
#' @param report A [validation_report()] data frame.
#' @param path The README to rewrite.
#' @param repo `owner/name` of the GitHub repository, for the workflow badge.
#' @return `path`, invisibly.
#' @export
validation_badges <- function(report, path = "README.md", repo = "SvL-1/mixdra") {
  n_match <- sum(report$kind == "match")
  n_pass  <- sum(report$kind == "match" & report$verdict == "pass")
  colour  <- if (n_pass == n_match && !any(report$verdict == "fail"))
               "brightgreen" else "red"

  badges <- c(
    sprintf(paste0("[![validation](https://github.com/%s/actions/workflows/",
                   "validation-report.yaml/badge.svg)]",
                   "(https://github.com/%s/actions/workflows/",
                   "validation-report.yaml)"), repo, repo),
    sprintf(paste0("[![reference values](https://img.shields.io/badge/",
                   "reference_values-%d%%2F%d-%s)](VALIDATION.md)"),
            n_pass, n_match, colour))

  lines <- readLines(path, warn = FALSE)
  s <- grep("<!-- validation-badges:start -->", lines, fixed = TRUE)
  e <- grep("<!-- validation-badges:end -->", lines, fixed = TRUE)
  if (length(s) != 1 || length(e) != 1 || e < s)
    stop("validation-badges markers not found (or not paired) in ", path,
         call. = FALSE)

  writeLines(c(lines[seq_len(s)], badges, lines[e:length(lines)]), path,
             useBytes = TRUE)
  invisible(path)
}
