# Markdown rendering of validation_report(), for the copy of the report that
# lives in the repository and renders natively on GitHub. Generated, never
# hand-edited: the CI workflow regenerates it and fails if the committed file
# differs, so a number in the repo cannot drift away from what the engine
# actually fits.
#
# Same data as validation_report_html(), traded down to what a markdown table
# can carry: per-row notes become footnotes under their table, and the tolerance
# headroom becomes a percentage instead of a bar.

.vm_cell <- function(x) gsub("|", "\\|", as.character(x), fixed = TRUE)

.vm_pct <- function(x) {
  if (is.na(x)) return("")
  if (x == 0) return("0")
  if (x < 0.001) return("<0.1%")
  paste0(trimws(formatC(100 * x, format = "fg", digits = 2)), "%")
}

# Literal characters rather than HTML entities: GitHub sanitises rendered
# markdown, and these have to survive that as well as a plain-text read.
.vm_status <- c(pass = "✓", fail = "✗", info = "–", missing = "?")

#' Render a validation report as markdown
#'
#' @param report A [validation_report()] data frame.
#' @param path File to write, or `NULL` to return the markdown as a character
#'   vector without writing.
#' @return The markdown lines, invisibly when written to a file.
#' @export
validation_report_md <- function(report, path = "VALIDATION.md") {
  reg <- validation_datasets()
  n_match <- sum(report$kind == "match")
  n_pass  <- sum(report$kind == "match" & report$verdict == "pass")
  n_fail  <- sum(report$verdict == "fail")
  n_div   <- sum(report$kind == "divergent")

  out <- c(
    "# Validation report",
    "",
    paste0("<!-- Generated by tools/validation-report.R. Do not edit by hand: ",
           "CI regenerates this file and fails if it differs. -->"),
    "",
    # Deliberately no timestamp: the file is regenerated on every CI run and
    # diffed against the committed copy, so a clock in it would fail that check
    # every time. Git history already records when the numbers last moved.
    sprintf(paste0("**%d of %d** published workbook values reproduced, ",
                   "%d deliberate difference%s, %d failure%s."),
            n_pass, n_match, n_div, if (n_div == 1) "" else "s",
            n_fail, if (n_fail == 1) "" else "s"),
    "",
    paste0("Every figure in the `mixdra` column was produced by re-fitting the ",
           "reference datasets with the current version of the package. The ",
           "`workbook` column comes from ",
           "[`inst/validation/oracles.csv`](inst/validation/oracles.csv), which ",
           "records each published value together with the sheet and column it ",
           "was read from, and which is also what the test suite asserts ",
           "against. A number cannot appear here without being tested, or be ",
           "tested without appearing here."),
    "",
    paste0("**Diff** is the distance from the published value. **Tol.** is how ",
           "much of the allowed tolerance that distance uses — a low ",
           "percentage is a strong agreement, near 100% only just qualifies. ",
           "Rows marked – make no point-value claim; their bounds are ",
           "asserted in the test suite instead."),
    "")

  for (ds in unique(report$dataset)) {
    d <- report[report$dataset == ds, , drop = FALSE]
    # Footnote only the rows that need explaining, numbered within the table.
    fn <- ifelse(nzchar(d$note), cumsum(nzchar(d$note)), NA_integer_)
    out <- c(out,
      sprintf("## %s", .vm_cell(reg[[ds]]$title %||% ds)),
      "",
      sprintf("`%s`", .vm_cell(ds)),
      "",
      "| Quantity | Workbook | mixdra | Diff | Tol. | |",
      "|---|---:|---:|---:|---:|:-:|")
    for (i in seq_len(nrow(d))) {
      tol <- suppressWarnings(as.numeric(d$tolerance[i]))
      used <- if (is.na(tol) || tol <= 0 || is.na(d$rel_diff[i])) ""
              else .vm_pct(d$rel_diff[i] / tol)
      out <- c(out, sprintf("| %s%s | %s | %s | %s | %s | %s |",
        .vm_cell(d$label[i]),
        if (is.na(fn[i])) "" else sprintf(" [^%s-%d]", ds, fn[i]),
        if (is.na(d$workbook[i])) "" else paste0("`", .vm_cell(.vh_num(d$workbook[i])), "`"),
        if (is.na(d$observed[i])) "" else paste0("`", .vm_cell(.vh_num(d$observed[i])), "`"),
        .vm_pct(d$rel_diff_workbook[i]), used,
        .vm_status[[d$verdict[i]]] %||% d$verdict[i]))
    }
    out <- c(out, "")
    for (i in which(!is.na(fn)))
      out <- c(out, sprintf("[^%s-%d]: %s%s", ds, fn[i],
                            if (nzchar(d$source[i]))
                              sprintf("*%s.* ", .vm_cell(d$source[i])) else "",
                            .vm_cell(d$note[i])), "")
  }

  out <- c(out,
    "## What this report does not show",
    "",
    paste0("Two implementations agreeing shows that they agree. It does not ",
           "show that either is right. That is what the synthetic recovery ",
           "tests are for: data is generated forward from known parameters ",
           "through the same model the fitter uses, and the engine has to ",
           "invert it back to those parameters. Those live in ",
           "[`tests/testthat/test-recovery.R`](tests/testthat/test-recovery.R)."),
    "",
    paste0("Reference data are *Folsomia candida* soil reproduction assays ",
           "(chlorpyrifos, microplastics, imidacloprid and FBSA, in mg/kg), ",
           "fitted with the Jonker et al. (2005) mixture dose-response method."),
    "")

  if (is.null(path)) return(out)
  writeLines(out, path, useBytes = TRUE)
  invisible(out)
}

#' Write the validation badges into a README
#'
#' Rewrites whatever sits between the `validation-badges` markers with badges
#' carrying the current score, so the figure in the README is generated rather
#' than typed. The CI workflow regenerates and diffs this file, which is what
#' stops the badge going stale while still claiming a number.
#'
#' @param report A [validation_report()] data frame.
#' @param path The README to rewrite.
#' @param repo `owner/name` of the GitHub repository, for the workflow badge.
#' @return `path`, invisibly.
#' @export
validation_badges <- function(report, path = "README.md", repo = "SvL-1/mixdra") {
  n_match <- sum(report$kind == "match")
  n_pass  <- sum(report$kind == "match" & report$verdict == "pass")
  colour  <- if (n_pass == n_match && !any(report$verdict == "fail"))
               "brightgreen" else "red"

  badges <- c(
    sprintf(paste0("[![validation](https://github.com/%s/actions/workflows/",
                   "validation-report.yaml/badge.svg)]",
                   "(https://github.com/%s/actions/workflows/",
                   "validation-report.yaml)"), repo, repo),
    sprintf(paste0("[![workbook values](https://img.shields.io/badge/",
                   "workbook_values-%d%%2F%d-%s)](VALIDATION.md)"),
            n_pass, n_match, colour))

  lines <- readLines(path, warn = FALSE)
  s <- grep("<!-- validation-badges:start -->", lines, fixed = TRUE)
  e <- grep("<!-- validation-badges:end -->", lines, fixed = TRUE)
  if (length(s) != 1 || length(e) != 1 || e < s)
    stop("validation-badges markers not found (or not paired) in ", path,
         call. = FALSE)

  writeLines(c(lines[seq_len(s)], badges, lines[e:length(lines)]), path,
             useBytes = TRUE)
  invisible(path)
}
